version: '3.8'

services:
  sozo-dev-website:
    container_name: website
    # The name of the image that will be created when building this container
    image: sozo-dev-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:3000